[workspace]
resolver = "3"
members = [
  "crates/app",
  "crates/core",
  "crates/pic-source-plugin-api",
  "crates/pic-source-plugin-host",
  "crates/storage",
  "crates/sync",
  "legacy/iced-app",
  "pic-source-plugins/sample-hello-pic-source"
]

[workspace.package]
edition = "2024"
repository = "https://github.com/MRDGH2821/Profile-Pulse"
license = "GPL-3.0-or-later"

[workspace.dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
base64 = "0.22"
chrono = { version = "0.4.42", features = ["serde"] }
directories = "6.0.0"
log = "0.4"
md5 = "0.7"
oauth2 = { version = "5.0", features = ["reqwest"] }
reqwest = { version = "0.12", default-features = false, features = [
  "rustls-tls"
] }
rusqlite = { version = "0.32", features = ["bundled"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tempfile = "3.24"
thiserror = "2.0"
tokio = { version = "1.49", features = ["fs", "macros", "rt-multi-thread"] }
toml = "0.8"
uuid = { version = "1.19", features = ["serde", "v4"] }
vobject = "0.8"
wasmtime = "31.0"
zip = "2.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = "thin"
codegen-units = 1

[profile.test]
opt-level = 1

[profile.dev-opt]
inherits = "dev"
opt-level = 1
