capabilities = []
id = "community.sample-hello-pic-source"
kind = "profile-pic-source"
min_host_version = "1.0.0"
name = "Sample Hello Pic Source"
runtime = "wasm"
version = "0.1.0"
website_match = []
